///|/ Copyright (c) preFlight 2025+ oozeBot, LLC - Ported to preFlight
///|/ Copyright (c) SuperSlicer 2023 @supermerill
///|/ Copyright (c) BambuStudio/BambuLab 2023 Mack @yongfang.bian
///|/ Copyright (c) OrcaSlicer 2023 @Noisyfox, @SoftFever
///|/
///|/ preFlight is based on PrusaSlicer and released under AGPLv3 or higher
///|/
#ifndef BRIMEARSPOINT_HPP
#define BRIMEARSPOINT_HPP

#include <libslic3r/Point.hpp>

namespace Slic3r
{

// An enum to keep track of where the current brim ear points on the ModelObject came from.
enum class BrimPointsStatus
{
    NoPoints,      // No points were generated so far.
    Generating,    // The autogeneration algorithm triggered, but not yet finished.
    AutoGenerated, // Points were autogenerated (i.e. copied from the backend).
    UserModified   // User has done some edits.
};

struct BrimPoint
{
    Vec3f pos;
    float head_front_radius;
    float overlap_percent;

    BrimPoint() : pos(Vec3f::Zero()), head_front_radius(0.f), overlap_percent(0.f) {}

    BrimPoint(float pos_x, float pos_y, float pos_z, float head_radius)
        : pos(pos_x, pos_y, pos_z), head_front_radius(head_radius), overlap_percent(0.f)
    {
    }

    BrimPoint(Vec3f position, float head_radius) : pos(position), head_front_radius(head_radius), overlap_percent(0.f)
    {
    }

    Vec3f transform(const Transform3d &trsf) const
    {
        Vec3d result = trsf * pos.cast<double>();
        return result.cast<float>();
    }

    bool operator==(const BrimPoint &sp) const
    {
        float rdiff = std::abs(head_front_radius - sp.head_front_radius);
        float odiff = std::abs(overlap_percent - sp.overlap_percent);
        return (pos == sp.pos) && rdiff < float(EPSILON) && odiff < float(EPSILON);
    }

    bool operator!=(const BrimPoint &sp) const { return !(sp == (*this)); }
    template<class Archive>
    void serialize(Archive &ar)
    {
        ar(pos, head_front_radius, overlap_percent);
    }
};

using BrimPoints = std::vector<BrimPoint>;

} // namespace Slic3r

#endif // BRIMEARSPOINT_HPP
