///|/ Copyright (c) preFlight 2025+ oozeBot, LLC
///|/ Copyright (c) Prusa Research 2019 - 2023 Oleksandra Iushchenko @YuSanka, Lukáš Matěna @lukasmatena, Pavel Mikuš @Godrak, Enrico Turri @enricoturri1966, Lukáš Hejl @hejllukas
///|/
///|/ preFlight is based on PrusaSlicer and released under AGPLv3 or higher
///|/
#ifndef slic3r_GLGizmoFdmSupports_hpp_
#define slic3r_GLGizmoFdmSupports_hpp_

#include "GLGizmoPainterBase.hpp"

#include "slic3r/GUI/I18N.hpp"

namespace Slic3r::GUI
{

class GLGizmoFdmSupports : public GLGizmoPainterBase
{
public:
    GLGizmoFdmSupports(GLCanvas3D &parent, const std::string &icon_filename, unsigned int sprite_id)
        : GLGizmoPainterBase(parent, icon_filename, sprite_id)
    {
    }

    void render_painter_gizmo() override;

protected:
    void on_render_input_window(float x, float y, float bottom_limit) override;
    std::string on_get_name() const override;

    wxString handle_snapshot_action_name(bool control_down, Button button_down) const override;

    TriangleStateType get_left_button_state_type() const override;
    TriangleStateType get_right_button_state_type() const override { return TriangleStateType::NONE; }
    ColorRGBA get_cursor_sphere_left_button_color() const override;

    std::string get_gizmo_entering_text() const override { return _u8L("Entering Paint-on supports"); }
    std::string get_gizmo_leaving_text() const override { return _u8L("Leaving Paint-on supports"); }
    std::string get_action_snapshot_name() const override { return _u8L("Paint-on supports editing"); }

private:
    bool on_init() override;
    void data_changed(bool is_serializing) override;

    void update_model_object() const override;
    void update_from_model_object() override;

    void on_opening() override
    {
        m_popup_render_count = 0;
        m_popup_width = 0.0f;
        m_popup_height = 0.0f;
    }
    void on_shutdown() override;
    PainterGizmoType get_painter_type() const override;

    void select_facets_by_angle(float threshold, bool block);

    // This map holds all translated description texts, so they can be easily referenced during layout calculations
    // etc. When language changes, GUI is recreated and this class constructed again, so the change takes effect.
    std::map<std::string, std::string> m_desc;

    bool waiting_for_autogenerated_supports = false;
    bool has_backend_supports();
    void auto_generate();
    void apply_data_from_backend();

    mutable int m_popup_render_count = 0;
    mutable float m_popup_width = 0.0f;
    mutable float m_popup_height = 0.0f;

    // 0 = Snug (blue), 1 = Grid (orange), 2 = Organic (green)
    int m_enforcer_type = 0;
};

} // namespace Slic3r::GUI

#endif // slic3r_GLGizmoFdmSupports_hpp_
