///|/ Copyright (c) preFlight 2025+ oozeBot, LLC
///|/ Copyright (c) Prusa Research 2016 - 2023 Oleksandra Iushchenko @YuSanka, Vojtěch Bubník @bubnikv, Filip Sykala @Jony01, David Kocík @kocikdav, Enrico Turri @enricoturri1966, Tomáš Mészáros @tamasmeszaros, Lukáš Matěna @lukasmatena, Vojtěch Král @vojtechkral
///|/ Copyright (c) 2019 Sijmen Schoon
///|/
///|/ preFlight is based on PrusaSlicer and released under AGPLv3 or higher
///|/
#pragma once

#include <string>

namespace Luminary
{

extern void set_logging_level(unsigned int level);
extern unsigned get_logging_level();

// Standard "generated by preFlight version xxx timestamp xxx" header string,
// to be placed at the top of generated files.
std::string header_generated();

// Standard "generated by preFlightGCodeViewer version xxx timestamp xxx" header string,
// to be placed at the top of generated files.
std::string header_gcodeviewer_generated();

// getpid platform wrapper
extern unsigned get_current_pid();

// The process allocator as the Windows start-up shim reported it ("tbbmalloc" or a "crt:<reason>" token),
// "crt:unreported" when no valid report exists, "system" on other platforms.
std::string process_allocator();

} // namespace Luminary
