///|/ Copyright (c) preFlight 2025+ oozeBot, LLC
///|/ Copyright (c) Prusa Research 2021 - 2023 Vojtěch Bubník @bubnikv, Lukáš Matěna @lukasmatena, Enrico Turri @enricoturri1966, Filip Sykala @Jony01
///|/
///|/ preFlight is based on PrusaSlicer and released under AGPLv3 or higher
///|/
#include "BuildVolume.hpp"

#include <boost/log/trivial.hpp>
#include <algorithm>
#include <cmath>
#include <limits>
#include <cassert>
#include <cstddef>

#include "luminary/geometry/clipper/ClipperUtils.hpp"
#include "luminary/geometry/index/AABBTreeLines.hpp"
#include "luminary/geometry/primitives/Line.hpp"
#include "luminary/geometry/hull/ConvexHull.hpp"
#include "luminary/geometry/primitives/Point.hpp"
#include "admesh/stl.h"
#include "luminary/geometry/primitives/BoundingBox.hpp"
#include "luminary/toolpath/extrusion/ExtrusionRole.hpp"
#include "luminary/geometry/circle/Circle.hpp"
#include "luminary/geometry/contours/Polygon.hpp"

#include "luminary/model/beds/MultipleBeds.hpp"

namespace Luminary
{

BuildVolume::BuildVolume(const std::vector<Vec2d> &bed_shape, const double max_print_height)
    : m_bed_shape(bed_shape), m_max_print_height(max_print_height)
{
    assert(max_print_height >= 0);

    m_polygon = Polygon::new_scale(bed_shape);

    // Calcuate various metrics of the input polygon.
    m_convex_hull = Geometry::convex_hull(m_polygon.points);
    m_bbox = get_extents(m_convex_hull);
    m_area = m_polygon.area();

    BoundingBoxf bboxf = get_extents(bed_shape);
    m_bboxf = BoundingBoxf3{to_3d(bboxf.min, 0.), to_3d(bboxf.max, max_print_height)};

    if (bed_shape.size() >= 4 &&
        std::abs((m_area - double(m_bbox.size().x()) * double(m_bbox.size().y()))) < sqr(SCALED_EPSILON))
    {
        // Square print bed, use the bounding box for collision detection.
        m_type = Type::Rectangle;
        m_circle.center = 0.5 * (m_bbox.min.cast<double>() + m_bbox.max.cast<double>());
        m_circle.radius = 0.5 * m_bbox.size().cast<double>().norm();
    }
    else if (bed_shape.size() > 3)
    {
        // Circle was discretized, formatted into text with limited accuracy, thus the circle was deformed.
        // RANSAC is slightly more accurate than the iterative Taubin / Newton method with such an input.
        //        m_circle = Geometry::circle_taubin_newton(bed_shape);
        m_circle = Geometry::circle_ransac(bed_shape);
        bool is_circle = true;
#ifndef NDEBUG
        // Measuring maximum absolute error of interpolating an input polygon with circle.
        double max_error = 0;
#endif // NDEBUG
        Vec2d prev = bed_shape.back();
        for (const Vec2d &p : bed_shape)
        {
#ifndef NDEBUG
            max_error = std::max(max_error, std::abs((p - m_circle.center).norm() - m_circle.radius));
#endif           // NDEBUG
            if ( // Polygon vertices must lie very close the circle.
                std::abs((p - m_circle.center).norm() - m_circle.radius) > 0.005 ||
                // Midpoints of polygon edges must not undercat more than 3mm. This corresponds to 72 edges per circle generated by BedShapePanel::update_shape().
                m_circle.radius - (0.5 * (prev + p) - m_circle.center).norm() > 3.)
            {
                is_circle = false;
                break;
            }
            prev = p;
        }
        if (is_circle)
        {
            m_type = Type::Circle;
            m_circle.center = scaled<double>(m_circle.center);
            m_circle.radius = scaled<double>(m_circle.radius);
        }
    }

    if (bed_shape.size() >= 3 && m_type == Type::Invalid)
    {
        // Circle check is not used for Convex / Custom shapes, fill it with something reasonable.
        m_circle = Geometry::smallest_enclosing_circle_welzl(m_convex_hull.points);
        m_type = (m_convex_hull.area() - m_area) < sqr(SCALED_EPSILON) ? Type::Convex : Type::Custom;
        // Initialize the top / bottom decomposition for inside convex polygon check. Do it with two different epsilons applied.
        auto convex_decomposition = [](const Polygon &in, double epsilon)
        {
            Polygon src = expand(in, float(epsilon)).front();
            std::vector<Vec2d> pts;
            pts.reserve(src.size());
            for (const Point &pt : src.points)
                pts.emplace_back(unscaled<double>(pt.cast<double>().eval()));
            return Geometry::decompose_convex_polygon_top_bottom(pts);
        };
        m_top_bottom_convex_hull_decomposition_scene = convex_decomposition(m_convex_hull, SceneEpsilon);
        m_top_bottom_convex_hull_decomposition_bed = convex_decomposition(m_convex_hull, BedEpsilon);
        if (m_type == Type::Custom)
        {
            // A concave bed is not described by its convex hull, so index the bed edges themselves, in
            // unscaled millimetres to match the coordinates the containment tests are called with. The
            // outline is not inflated: the epsilon of a test is applied as a distance to these edges.
            Linesf outline;
            outline.reserve(m_polygon.size());
            for (size_t i = 0; i < m_polygon.points.size(); ++i)
            {
                const Point &a = m_polygon.points[i];
                const Point &b = m_polygon.points[(i + 1) % m_polygon.points.size()];
                outline.emplace_back(unscaled<double>(a.cast<double>().eval()),
                                     unscaled<double>(b.cast<double>().eval()));
            }
            m_bed_outline = std::make_shared<const AABBTreeLines::LinesDistancer<Linef>>(std::move(outline));
        }
    }

    BOOST_LOG_TRIVIAL(debug) << "BuildVolume bed_shape clasified as: " << this->type_name();
}

bool BuildVolume::point_inside_bed_outline(const std::pair<std::vector<Vec2d>, std::vector<Vec2d>> &hull_decomposition,
                                           double epsilon, const Vec2d &point) const
{
    // Outside the convex hull inflated by epsilon is outside any bed the hull encloses.
    if (!Geometry::inside_convex_polygon(hull_decomposition, point))
        return false;
    if (m_type != Type::Custom || !m_bed_outline)
        return true;
    // Inside the outline or on it counts as inside, and so does a point within epsilon of an edge, which
    // is the tolerance the hull path grants.
    if (m_bed_outline->outside(point) <= 0)
        return true;
    return m_bed_outline->distance_from_lines<false>(point) <= epsilon;
}

// Trim the input transformed triangle mesh with print bed and test the remaining vertices with is_inside callback.
// Return inside / colliding / outside state.
template<typename InsideFn>
BuildVolume::ObjectState object_state_templ(const indexed_triangle_set &its, const Transform3f &trafo,
                                            bool may_be_below_bed, InsideFn is_inside)
{
    size_t num_inside = 0;
    size_t num_above = 0;
    bool inside = false;
    bool outside = false;
    static constexpr const auto world_min_z = float(-BuildVolume::SceneEpsilon);

    if (may_be_below_bed)
    {
        // Slower test, needs to clip the object edges with the print bed plane.
        // 1) Allocate transformed vertices with their position with respect to print bed surface.
        std::vector<char> sides;
        sides.reserve(its.vertices.size());

        const auto sign = [](const stl_vertex &pt)
        {
            return pt.z() > world_min_z ? 1 : pt.z() < world_min_z ? -1 : 0;
        };

        for (const stl_vertex &v : its.vertices)
        {
            const stl_vertex pt = trafo * v;
            const int s = sign(pt);
            sides.emplace_back(s);
            if (s >= 0)
            {
                // Vertex above or on print bed surface. Test whether it is inside the build volume.
                ++num_above;
                if (is_inside(pt))
                    ++num_inside;
            }
        }

        if (num_above == 0)
            // Special case, the object is completely below the print bed, thus it is outside,
            // however we want to allow an object to be still printable if some of its parts are completely below the print bed.
            return BuildVolume::ObjectState::Below;

        // 2) Calculate intersections of triangle edges with the build surface.
        inside = num_inside > 0;
        outside = num_inside < num_above;
        if (num_above < its.vertices.size() && !(inside && outside))
        {
            // Not completely above the build surface and status may still change by testing edges intersecting the build platform.
            for (const stl_triangle_vertex_indices &tri : its.indices)
            {
                const int s[3] = {sides[tri(0)], sides[tri(1)], sides[tri(2)]};
                if (std::min(s[0], std::min(s[1], s[2])) < 0 && std::max(s[0], std::max(s[1], s[2])) > 0)
                {
                    // Some edge of this triangle intersects the build platform. Calculate the intersection.
                    int iprev = 2;
                    for (int iedge = 0; iedge < 3; ++iedge)
                    {
                        if (s[iprev] * s[iedge] == -1)
                        {
                            // edge intersects the build surface. Calculate intersection point.
                            const stl_vertex p1 = trafo * its.vertices[tri(iprev)];
                            const stl_vertex p2 = trafo * its.vertices[tri(iedge)];
                            assert(sign(p1) == s[iprev]);
                            assert(sign(p2) == s[iedge]);
                            assert((p1.z() - world_min_z) * (p2.z() - world_min_z) < 0);
                            // Edge crosses the z plane. Calculate intersection point with the plane.
                            const float t = (world_min_z - p1.z()) / (p2.z() - p1.z());
                            (is_inside(
                                 Vec3f(p1.x() + (p2.x() - p1.x()) * t, p1.y() + (p2.y() - p1.y()) * t, world_min_z))
                                 ? inside
                                 : outside) = true;
                        }
                        iprev = iedge;
                    }
                    if (inside && outside)
                        break;
                }
            }
        }
    }
    else
    {
        // Much simpler and faster code, not clipping the object with the print bed.
        assert(!may_be_below_bed);
        num_above = its.vertices.size();
        for (const stl_vertex &v : its.vertices)
        {
            const stl_vertex pt = trafo * v;
            assert(pt.z() >= world_min_z);
            if (is_inside(pt))
                ++num_inside;
        }
        inside = num_inside > 0;
        outside = num_inside < num_above;
    }

    return inside ? (outside ? BuildVolume::ObjectState::Colliding : BuildVolume::ObjectState::Inside)
                  : BuildVolume::ObjectState::Outside;
}

BuildVolume::ObjectState BuildVolume::object_state(const indexed_triangle_set &its, const Transform3f &trafo_orig,
                                                   bool may_be_below_bed, bool ignore_bottom, int *bed_idx) const
{
    ObjectState out = ObjectState::Outside;
    if (bed_idx)
        *bed_idx = -1;

    // When loading an old project with more than the maximum number of beds,
    // we still want to move the objects to the respective positions.
    // Max beds number is momentarily increased when doing the rearrange, so use it.
    const int max_bed = s_multiple_beds.get_loading_project_flag()
                            ? s_multiple_beds.get_number_of_beds() - 1
                            : std::min(s_multiple_beds.get_number_of_beds(), s_multiple_beds.get_max_beds() - 1);

    for (int bed_id = 0; bed_id <= max_bed; ++bed_id)
    {
        Transform3f trafo = trafo_orig;
        trafo.pretranslate(-s_multiple_beds.get_bed_translation(bed_id).cast<float>());

        switch (m_type)
        {
        case Type::Rectangle:
        {
            BoundingBox3Base<Vec3d> build_volume = this->bounding_volume().inflated(SceneEpsilon);
            if (m_max_print_height == 0.0)
                build_volume.max.z() = std::numeric_limits<double>::max();
            if (ignore_bottom)
                build_volume.min.z() = -std::numeric_limits<double>::max();
            BoundingBox3Base<Vec3f> build_volumef(build_volume.min.cast<float>(), build_volume.max.cast<float>());
            // A non-convex object crossing a rectangular build volume is not classified exactly by this test.
            out = object_state_templ(its, trafo, may_be_below_bed,
                                     [build_volumef](const Vec3f &pt) { return build_volumef.contains(pt); });
            break;
        }
        case Type::Circle:
        {
            Geometry::Circlef circle{unscaled<float>(m_circle.center), unscaled<float>(m_circle.radius + SceneEpsilon)};
            out = m_max_print_height == 0.0
                      ? object_state_templ(its, trafo, may_be_below_bed,
                                           [circle](const Vec3f &pt) { return circle.contains(to_2d(pt)); })
                      : object_state_templ(its, trafo, may_be_below_bed,
                                           [circle, z = m_max_print_height + SceneEpsilon](const Vec3f &pt)
                                           { return pt.z() < z && circle.contains(to_2d(pt)); });
            break;
        }
        case Type::Convex:
        // A convex outline is answered by the hull decomposition alone; a custom one is tested against
        // its own edges, so a vertex in a concave notch of the bed reads as outside.
        case Type::Custom:
            out = m_max_print_height == 0.0
                      ? object_state_templ(its, trafo, may_be_below_bed,
                                           [this](const Vec3f &pt)
                                           {
                                               return this->point_inside_bed_outline(
                                                   m_top_bottom_convex_hull_decomposition_scene, SceneEpsilon,
                                                   to_2d(pt).cast<double>());
                                           })
                      : object_state_templ(its, trafo, may_be_below_bed,
                                           [this, z = m_max_print_height + SceneEpsilon](const Vec3f &pt)
                                           {
                                               return pt.z() < z && this->point_inside_bed_outline(
                                                                        m_top_bottom_convex_hull_decomposition_scene,
                                                                        SceneEpsilon, to_2d(pt).cast<double>());
                                           });
            break;
        case Type::Invalid:
        default:
            out = ObjectState::Inside;
            break;
        }

        if (out != ObjectState::Outside)
        {
            if (bed_idx)
                *bed_idx = bed_id;
            break;
        }
    }

    return out;
}

BuildVolume::ObjectState BuildVolume::volume_state_bbox(const BoundingBoxf3 volume_bbox_orig, bool ignore_bottom,
                                                        int *bed_idx) const
{
    assert(m_type == Type::Rectangle);
    BoundingBox3Base<Vec3d> build_volume = this->bounding_volume().inflated(SceneEpsilon);
    if (m_max_print_height == 0.0)
        build_volume.max.z() = std::numeric_limits<double>::max();
    if (ignore_bottom)
        build_volume.min.z() = -std::numeric_limits<double>::max();

    ObjectState state = ObjectState::Outside;
    int obj_bed_id = -1;
    for (int bed_id = 0; bed_id <= std::min(s_multiple_beds.get_number_of_beds(), s_multiple_beds.get_max_beds() - 1);
         ++bed_id)
    {
        BoundingBoxf3 volume_bbox = volume_bbox_orig;
        volume_bbox.translate(-s_multiple_beds.get_bed_translation(bed_id));

        state = build_volume.max.z() <= -SceneEpsilon  ? ObjectState::Below
                : build_volume.contains(volume_bbox)   ? ObjectState::Inside
                : build_volume.intersects(volume_bbox) ? ObjectState::Colliding
                                                       : ObjectState::Outside;
        if (state != ObjectState::Outside)
        {
            obj_bed_id = bed_id;
            break;
        }
    }

    if (bed_idx)
        *bed_idx = obj_bed_id;
    return state;
}

template<typename Fn>
inline bool all_inside_vertices_normals_interleaved(const std::vector<float> &paths, Fn fn)
{
    for (auto it = paths.begin(); it != paths.end();)
    {
        it += 3;
        if (!fn({*it, *(it + 1), *(it + 2)}))
            return false;
        it += 3;
    }
    return true;
}

std::string_view BuildVolume::type_name(Type type)
{
    using namespace std::literals;
    switch (type)
    {
    case Type::Invalid:
        return "Invalid"sv;
    case Type::Rectangle:
        return "Rectangle"sv;
    case Type::Circle:
        return "Circle"sv;
    case Type::Convex:
        return "Convex"sv;
    case Type::Custom:
        return "Custom"sv;
    }
    // make visual studio happy
    assert(false);
    return {};
}

} // namespace Luminary
